version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - printf '{"CODEBUILD_RESOLVED_SOURCE_VERSION":"%s"}' ${CODEBUILD_RESOLVED_SOURCE_VERSION}
  build:
    commands:
      - printf '{"repository_uri":"%s"}' ${REPOSITORY_URI}
      - docker build --tag "305890642658.dkr.ecr.us-east-2.amazonaws.com/ecs-c-repos-r9v47t2mloef:${TAG}" .
  post_build:
    commands:
      - docker push "${REPOSITORY_URI}:${TAG}"
      - printf '{"tag":"%s"}' $TAG > build.json
artifacts:
  files: build.json
