version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login)
  build:
    commands:
      - docker build --tag "305890642658.dkr.ecr.us-east-2.amazonaws.com/cicd-demo-ecr-01:1" .
  post_build:
    commands:
      - docker push "305890642658.dkr.ecr.us-east-2.amazonaws.com/cicd-demo-ecr-01:1"
